<?php

declare(strict_types=1);

return [
    'ready-stock' => [
        'title' => 'Ready Stock',
        'eyebrow' => 'Fast procurement',
        'description' => 'Review ready-stock candidates, then confirm inventory, lead time and commercial terms with Artdon.',
        'template' => 'listing',
        'items' => [
            'all-ready-stock' => ['title' => 'All Ready Stock', 'description' => 'Browse products and accessories flagged for ready-stock review.'],
            'track-lighting' => ['title' => 'Track Lighting', 'description' => 'Track spotlights, wall washers and linear modules ready to ship.'],
            'downlights' => ['title' => 'Downlights', 'description' => 'Fixed, adjustable and trimless downlight candidates for inventory confirmation.'],
            'magnetic-system' => ['title' => 'Magnetic System', 'description' => 'Magnetic tracks, luminaires, drivers and connectors.'],
            'linear-lighting' => ['title' => 'Linear Lighting', 'description' => 'Linear fixtures for retail, office and hospitality projects.'],
            'accessories' => ['title' => 'Accessories', 'description' => 'Optics, reflectors, drivers, connectors and mounting accessories.'],
            'new-arrival' => ['title' => 'New Arrival', 'description' => 'New-product and recently listed configuration candidates.'],
            'clearance' => ['title' => 'Clearance', 'description' => 'Clearance candidates subject to quantity and price confirmation.'],
        ],
    ],
    'products' => [
        'title' => 'Products',
        'eyebrow' => 'Complete product system',
        'description' => 'Luminaires, drivers, tracks, accessories and spare parts in one procurement catalogue.',
        'template' => 'listing',
        'items' => [
            'track-lighting' => [
                'title' => 'Track Lighting',
                'description' => 'Flexible track luminaires for retail, galleries, hospitality and commercial spaces.',
                'items' => [
                    'track-spot' => ['title' => 'Track Spot'],
                    'track-linear' => ['title' => 'Track Linear'],
                    'wall-washer' => ['title' => 'Wall Washer'],
                    'zoom' => ['title' => 'Zoom'],
                    'pendant' => ['title' => 'Pendant'],
                    'accessories' => ['title' => 'Accessories'],
                ],
            ],
            'recessed-downlights' => [
                'title' => 'Recessed Downlights',
                'description' => 'Architectural downlights with controlled glare and multiple optics.',
                'items' => [
                    'fixed' => ['title' => 'Fixed'],
                    'adjustable' => ['title' => 'Adjustable'],
                    'trimless' => ['title' => 'Trimless'],
                    'ip65' => ['title' => 'IP65'],
                    'high-ceiling' => ['title' => 'High Ceiling'],
                    'mini' => ['title' => 'Mini'],
                ],
            ],
            'magnetic' => ['title' => 'Magnetic'],
            'linear' => ['title' => 'Linear'],
            'surface' => ['title' => 'Surface'],
            'pendant' => ['title' => 'Pendant'],
            'outdoor' => ['title' => 'Outdoor'],
            'driver' => ['title' => 'Driver'],
            'track-rail' => ['title' => 'Track Rail'],
            'strip' => ['title' => 'Strip'],
            'sensor' => ['title' => 'Sensor'],
            'emergency' => ['title' => 'Emergency'],
            'accessories' => ['title' => 'Accessories'],
            'spare-parts' => ['title' => 'Spare Parts'],
            'all-products' => ['title' => 'All Products'],
        ],
    ],
    'solutions' => [
        'title' => 'Solutions',
        'eyebrow' => 'Application expertise',
        'description' => 'Application-led lighting guidance, recommended product systems and project resources.',
        'template' => 'solution',
        'items' => [
            'retail' => ['title' => 'Retail'],
            'hospitality' => ['title' => 'Hospitality'],
            'office' => ['title' => 'Office'],
            'residential' => ['title' => 'Residential'],
            'museum' => ['title' => 'Museum'],
            'gallery' => ['title' => 'Gallery'],
            'supermarket' => ['title' => 'Supermarket'],
            'shopping-mall' => ['title' => 'Shopping Mall'],
            'restaurant' => ['title' => 'Restaurant'],
            'airport' => ['title' => 'Airport'],
            'education' => ['title' => 'Education'],
            'healthcare' => ['title' => 'Healthcare'],
        ],
    ],
    'projects' => [
        'title' => 'Projects',
        'eyebrow' => 'Proof in application',
        'description' => 'Project references connecting design intent, selected products, photometrics and outcomes.',
        'template' => 'project',
        'items' => [
            'retail' => ['title' => 'Retail'],
            'hospitality' => ['title' => 'Hospitality'],
            'office' => ['title' => 'Office'],
            'museum' => ['title' => 'Museum'],
            'residential' => ['title' => 'Residential'],
            'commercial' => ['title' => 'Commercial'],
            'airport' => ['title' => 'Airport'],
            'all-projects' => ['title' => 'All Projects'],
        ],
    ],
    'resources' => [
        'title' => 'Resources',
        'eyebrow' => 'Technical library',
        'description' => 'Searchable product documentation for designers, engineers and procurement teams.',
        'template' => 'resource',
        'items' => [
            'catalogue' => ['title' => 'Catalogue'],
            'series-brochure' => ['title' => 'Series Brochure'],
            'datasheet' => ['title' => 'Datasheet'],
            'ies' => ['title' => 'IES'],
            'bim' => ['title' => 'BIM'],
            'cad' => ['title' => 'CAD'],
            'installation' => ['title' => 'Installation'],
            'certificates' => ['title' => 'Certificates'],
            'warranty' => ['title' => 'Warranty'],
            'videos' => ['title' => 'Videos'],
            'downloads' => ['title' => 'Downloads'],
            'faq' => ['title' => 'FAQ'],
        ],
    ],
    'learn' => [
        'title' => 'Learn',
        'eyebrow' => 'Lighting knowledge',
        'description' => 'Practical guidance for product selection, design, installation and procurement.',
        'template' => 'learn',
        'items' => [
            'lighting-basics' => ['title' => 'Lighting Basics'],
            'product-guide' => ['title' => 'Product Guide'],
            'installation' => ['title' => 'Installation'],
            'design-ideas' => ['title' => 'Design Ideas'],
            'buying-guide' => ['title' => 'Buying Guide'],
            'industry-news' => ['title' => 'Industry News'],
            'company-news' => ['title' => 'Company News'],
            'videos' => ['title' => 'Videos'],
        ],
    ],
    'ai' => [
        'title' => 'AI Assistant',
        'eyebrow' => 'Faster product decisions',
        'description' => 'Guided tools for finding products, estimating quantities and selecting compatible components.',
        'template' => 'ai',
        'items' => [
            'lighting-simulation' => [
                'title' => 'Lighting Simulation',
                'path' => 'lighting-simulation',
                'description' => 'Use product IES photometry to estimate direct illuminance, layout and uniformity.',
            ],
            'product-finder' => ['title' => 'Product Finder'],
            'lighting-calculator' => ['title' => 'Lighting Calculator'],
            'beam-angle-selector' => ['title' => 'Beam Angle Selector'],
            'driver-selector' => ['title' => 'Driver Selector'],
            'compare-products' => ['title' => 'Compare Products'],
            'ai-consultant' => ['title' => 'AI Consultant'],
        ],
    ],
    'procurement' => [
        'title' => 'Procurement',
        'eyebrow' => 'From requirement to confirmed order',
        'description' => 'Dedicated services for samples, RFQs, project packages, OEM and bulk orders.',
        'template' => 'procurement',
        'items' => [
            'quick-rfq' => ['title' => 'Quick RFQ'],
            'sample-order' => ['title' => 'Sample Order'],
            'ready-stock' => ['title' => 'Ready Stock'],
            'oem' => ['title' => 'OEM'],
            'odm' => ['title' => 'ODM'],
            'bulk-order' => ['title' => 'Bulk Order'],
            'project-package' => ['title' => 'Project Package'],
            'procurement-service' => ['title' => 'Procurement Service'],
        ],
    ],
    'support' => [
        'title' => 'Support',
        'eyebrow' => 'Clear procurement policies',
        'description' => 'Shipping, payment, lead time, quality and technical support information.',
        'template' => 'support',
        'items' => [
            'shipping' => ['title' => 'Shipping'],
            'payment' => ['title' => 'Payment'],
            'lead-time' => ['title' => 'Lead Time'],
            'warranty' => ['title' => 'Warranty'],
            'returns' => ['title' => 'Returns'],
            'quality' => ['title' => 'Quality'],
            'faq' => ['title' => 'FAQ'],
            'contact' => ['title' => 'Contact'],
            'downloads' => ['title' => 'Downloads'],
            'technical-support' => ['title' => 'Technical Support'],
        ],
    ],
    'about' => [
        'title' => 'About',
        'eyebrow' => 'Manufacturing partner',
        'description' => 'A commercial lighting manufacturer focused on configurable products and dependable delivery.',
        'template' => 'about',
        'items' => [
            'company' => ['title' => 'Company'],
            'factory' => ['title' => 'Factory'],
            'team' => ['title' => 'Team'],
            'manufacturing' => ['title' => 'Manufacturing'],
            'quality' => ['title' => 'Quality'],
            'exhibition' => ['title' => 'Exhibition'],
            'careers' => ['title' => 'Careers'],
            'contact' => ['title' => 'Contact'],
        ],
    ],
    'account' => [
        'title' => 'My Account',
        'eyebrow' => 'Procurement workspace',
        'description' => 'Track requests, quotes, orders, downloads and saved product selections.',
        'template' => 'account',
        'items' => [
            'dashboard' => ['title' => 'Dashboard'],
            'orders' => ['title' => 'Orders'],
            'quotes' => ['title' => 'Quotes'],
            'wishlist' => ['title' => 'Wishlist'],
            'compare' => ['title' => 'Compare'],
            'downloads' => ['title' => 'Downloads'],
            'address' => ['title' => 'Address'],
            'settings' => ['title' => 'Settings'],
        ],
    ],
];
