<?php

declare(strict_types=1);

return [
    [
        'sku' => 'AL1010', 'name' => 'Recessed Downlight', 'series' => 'AL10',
        'category' => 'recessed-downlights', 'subcategory' => 'fixed', 'stock_group' => 'downlights',
        'price' => 48.00, 'stock' => 860, 'lead_time' => '3–5 days', 'moq' => 20,
        'image' => 'downlight.svg', 'badge' => 'Demo stock', 'new' => false, 'clearance' => false,
        'summary' => 'Deep anti-glare architectural downlight for retail, hospitality and office projects.',
        'features' => ['UGR<16', 'CRI 90+', 'DALI-2 option', '5-year warranty'],
        'specs' => ['Power' => '6W / 10W / 15W / 20W', 'Cut-out' => 'Ø75–80mm', 'Beam' => '15° / 24° / 36° / 60°', 'CCT' => '2700K–5000K', 'IP' => 'IP65', 'Finish' => 'White / Black'],
    ],
    [
        'sku' => 'AL1011', 'name' => 'Adjustable Downlight', 'series' => 'AL10',
        'category' => 'recessed-downlights', 'subcategory' => 'adjustable', 'stock_group' => 'downlights',
        'price' => 62.00, 'stock' => 420, 'lead_time' => '3–5 days', 'moq' => 20,
        'image' => 'adjustable.svg', 'badge' => 'Demo stock', 'new' => true, 'clearance' => false,
        'summary' => 'Precision adjustable downlight with flexible aiming and controlled glare.',
        'features' => ['355° rotation', '30° tilt', 'CRI 90+', 'Tool-free optics'],
        'specs' => ['Power' => '10W / 15W / 20W', 'Cut-out' => 'Ø85mm', 'Beam' => '18° / 24° / 36°', 'CCT' => '2700K–4000K', 'IP' => 'IP44', 'Finish' => 'White / Black'],
    ],
    [
        'sku' => 'AT2020', 'name' => 'Track Spotlight', 'series' => 'AT20',
        'category' => 'track-lighting', 'subcategory' => 'track-spot', 'stock_group' => 'track-lighting',
        'price' => 68.00, 'stock' => 620, 'lead_time' => '3–5 days', 'moq' => 20,
        'image' => 'track.svg', 'badge' => 'Demo catalogue', 'new' => false, 'clearance' => false,
        'summary' => 'Compact track spotlight with interchangeable optics and high visual comfort.',
        'features' => ['15°–60° optics', 'CRI 90+', 'Global track adapters', 'DALI option'],
        'specs' => ['Power' => '12W / 18W / 25W', 'Adapter' => '2/3/4-wire', 'Beam' => '15° / 24° / 36° / 60°', 'CCT' => '2700K–5000K', 'CRI' => 'Ra90 / Ra95', 'Finish' => 'White / Black'],
    ],
    [
        'sku' => 'ATL2030', 'name' => 'Track Linear', 'series' => 'ATL20',
        'category' => 'track-lighting', 'subcategory' => 'track-linear', 'stock_group' => 'track-lighting',
        'price' => 86.00, 'stock' => 280, 'lead_time' => '5–7 days', 'moq' => 20,
        'image' => 'track-linear.svg', 'badge' => 'Demo item', 'new' => true, 'clearance' => false,
        'summary' => 'Continuous track linear module for shelves, aisles and general illumination.',
        'features' => ['Low glare lens', 'Seamless visual line', 'DALI option', 'Multiple lengths'],
        'specs' => ['Power' => '20W / 30W / 40W', 'Length' => '600 / 900 / 1200mm', 'Beam' => '30° / 60° / Batwing', 'CCT' => '3000K–5000K', 'CRI' => 'Ra90', 'Finish' => 'White / Black'],
    ],
    [
        'sku' => 'MW3010', 'name' => 'Magnetic Wall Washer', 'series' => 'MW30',
        'category' => 'magnetic', 'subcategory' => 'wall-washer', 'stock_group' => 'magnetic-system',
        'price' => 78.00, 'stock' => 310, 'lead_time' => '5–7 days', 'moq' => 20,
        'image' => 'magnetic.svg', 'badge' => 'Demo stock', 'new' => false, 'clearance' => false,
        'summary' => '48V magnetic wall washer for uniform vertical illumination.',
        'features' => ['48V safe voltage', 'Anti-glare louvre', 'Tool-free mounting', 'PWM / DALI'],
        'specs' => ['Power' => '12W / 18W / 24W', 'Voltage' => 'DC48V', 'Beam' => 'Asymmetric', 'CCT' => '2700K–4000K', 'CRI' => 'Ra90', 'Finish' => 'Black'],
    ],
    [
        'sku' => 'LN4010', 'name' => 'Architectural Linear Light', 'series' => 'LN40',
        'category' => 'linear', 'subcategory' => 'linear', 'stock_group' => 'linear-lighting',
        'price' => 96.00, 'stock' => 190, 'lead_time' => '7–10 days', 'moq' => 10,
        'image' => 'linear.svg', 'badge' => 'Demo project item', 'new' => false, 'clearance' => false,
        'summary' => 'Suspended or surface architectural linear system with continuous light.',
        'features' => ['Custom lengths', 'Micro-prismatic option', 'Up/down light', 'Emergency option'],
        'specs' => ['Power' => '20–80W', 'Length' => '600–2400mm', 'Optic' => 'Opal / UGR<19', 'CCT' => '3000K–5000K', 'CRI' => 'Ra90', 'Finish' => 'White / Black / Custom'],
    ],
    [
        'sku' => 'PD5010', 'name' => 'Decorative Pendant', 'series' => 'PD50',
        'category' => 'pendant', 'subcategory' => 'pendant', 'stock_group' => 'linear-lighting',
        'price' => 88.00, 'stock' => 95, 'lead_time' => '7–10 days', 'moq' => 10,
        'image' => 'pendant.svg', 'badge' => 'Demo item', 'new' => true, 'clearance' => false,
        'summary' => 'Minimal pendant luminaire for counters, dining areas and hospitality spaces.',
        'features' => ['Soft ambient light', 'Adjustable cable', 'Multiple finishes', 'Dimming option'],
        'specs' => ['Power' => '12W / 18W', 'Diameter' => 'Ø180 / Ø250mm', 'Beam' => '40°', 'CCT' => '2700K–4000K', 'CRI' => 'Ra90', 'Finish' => 'Black / Gold / Custom'],
    ],
    [
        'sku' => 'OD6010', 'name' => 'Outdoor Wall Light', 'series' => 'OD60',
        'category' => 'outdoor', 'subcategory' => 'wall-light', 'stock_group' => 'accessories',
        'price' => 72.00, 'stock' => 140, 'lead_time' => '7–10 days', 'moq' => 20,
        'image' => 'outdoor.svg', 'badge' => 'IP65', 'new' => false, 'clearance' => false,
        'summary' => 'Durable architectural wall light with controlled up/down distribution.',
        'features' => ['IP65', 'Salt spray tested', 'Adjustable beam', 'Outdoor coating'],
        'specs' => ['Power' => '10W / 16W / 24W', 'Voltage' => 'AC220–240V', 'Beam' => '10°–60°', 'CCT' => '2700K–4000K', 'IP' => 'IP65', 'Finish' => 'Black / Grey'],
    ],
    [
        'sku' => 'DR7010', 'name' => 'DALI-2 LED Driver', 'series' => 'DR70',
        'category' => 'driver', 'subcategory' => 'dali', 'stock_group' => 'accessories',
        'price' => 26.00, 'stock' => 1250, 'lead_time' => '2–3 days', 'moq' => 50,
        'image' => 'driver.svg', 'badge' => 'Demo stock', 'new' => false, 'clearance' => false,
        'summary' => 'Flicker-free constant-current driver with DALI-2 dimming.',
        'features' => ['DALI-2', 'Flicker-free', 'Push dim', '5-year warranty'],
        'specs' => ['Power' => '15W / 25W / 40W', 'Input' => '220–240V', 'Output' => '250–1050mA', 'Dimming' => 'DALI-2 / Push', 'PF' => '>0.95', 'Warranty' => '5 years'],
    ],
    [
        'sku' => 'TR8010', 'name' => '3-Circuit Track Rail', 'series' => 'TR80',
        'category' => 'track-rail', 'subcategory' => 'track-rail', 'stock_group' => 'accessories',
        'price' => 18.00, 'stock' => 2100, 'lead_time' => '2–3 days', 'moq' => 50,
        'image' => 'track-rail.svg', 'badge' => 'Demo stock', 'new' => false, 'clearance' => false,
        'summary' => 'Commercial three-circuit track rail with complete connector system.',
        'features' => ['1m / 2m / 3m', 'Copper conductors', 'Surface / suspended', 'Full connectors'],
        'specs' => ['Length' => '1m / 2m / 3m', 'Circuit' => '3-circuit', 'Voltage' => '220–240V', 'Material' => 'Aluminium + copper', 'Mounting' => 'Surface / Suspended', 'Finish' => 'White / Black'],
    ],
    [
        'sku' => 'AC9010', 'name' => 'Honeycomb Louvre', 'series' => 'AC90',
        'category' => 'accessories', 'subcategory' => 'optics', 'stock_group' => 'accessories',
        'price' => 6.80, 'stock' => 1800, 'lead_time' => '2–3 days', 'moq' => 100,
        'image' => 'accessory.svg', 'badge' => 'Accessory', 'new' => false, 'clearance' => false,
        'summary' => 'Anti-glare honeycomb accessory for compatible downlights and spotlights.',
        'features' => ['Reduces glare', 'Snap-in mounting', 'Multiple sizes', 'Black finish'],
        'specs' => ['Diameter' => 'Ø45 / Ø55 / Ø65mm', 'Material' => 'Aluminium', 'Compatibility' => 'AL10 / AT20', 'Finish' => 'Black', 'Packaging' => '100 pcs/carton', 'Warranty' => '2 years'],
    ],
    [
        'sku' => 'SP9020', 'name' => 'Replacement Reflector', 'series' => 'SP90',
        'category' => 'spare-parts', 'subcategory' => 'reflector', 'stock_group' => 'accessories',
        'price' => 4.20, 'stock' => 600, 'lead_time' => '2–3 days', 'moq' => 100,
        'image' => 'reflector.svg', 'badge' => 'Demo clearance', 'new' => false, 'clearance' => true,
        'summary' => 'Replacement reflector in multiple finishes for selected downlight series.',
        'features' => ['Tool-free replacement', 'Multiple finishes', 'Batch colour matching', 'Protective packing'],
        'specs' => ['Diameter' => 'Ø55 / Ø65 / Ø75mm', 'Material' => 'Aluminium', 'Compatibility' => 'AL10 series', 'Finish' => 'Black / White / Gold', 'MOQ' => '100 pcs', 'Warranty' => '1 year'],
    ],
];
