<?php declare(strict_types=1); $section=$sections['account']; $view=$page['slug'] ?? 'dashboard'; ?>
<section class="account-page"><div class="container account-layout"><aside class="account-sidebar"><div class="account-profile"><div class="avatar">DB</div><div><strong>Demo Buyer Company</strong><span>Buyer account · Demo</span></div></div><nav><?php foreach($section['items'] as $slug=>$item): ?><a class="<?= $slug===$view?'is-active':'' ?>" href="<?= url('account/'.$slug) ?>"><?= icon(match($slug){'orders'=>'cart','quotes'=>'quote','wishlist'=>'heart','compare'=>'compare','downloads'=>'download','address'=>'location','settings'=>'user',default=>'project'}) ?><?= e($item['title']) ?><span><?= icon('chevron') ?></span></a><?php endforeach; ?></nav><a class="account-help" href="<?= url('support') ?>"><strong>Need support?</strong><span>Contact sales or technical support.</span><?= icon('arrow') ?></a></aside><div class="account-main"><?= breadcrumb($page) ?><div class="account-header"><div><span class="eyebrow">My Account</span><h1><?= e($page['title']) ?></h1><p>Demo customer centre for procurement activity.</p></div><a class="button button-dark" href="<?= url('procurement/quick-rfq') ?>">New RFQ</a></div>
<?php if($view==='dashboard'): ?>
<div class="account-stat-grid"><div><span>Open quotes</span><strong>3</strong><small>1 awaiting confirmation</small></div><div><span>Active orders</span><strong>5</strong><small>2 in production</small></div><div><span>Saved products</span><strong>12</strong><small>Across 4 categories</small></div><div><span>Recent downloads</span><strong>18</strong><small>IES and datasheets</small></div></div><div class="account-grid"><section class="account-panel"><div class="panel-head"><h2>Recent orders</h2><a href="<?= url('account/orders') ?>">View all</a></div><div class="order-list"><?php foreach([['WO-20260722-0001','Under review','USD 8,600'],['SO-20260718-0028','In production','USD 24,380'],['SO-20260630-0017','Shipped','USD 12,940']] as [$no,$status,$amount]): ?><a href="#"><span><strong><?= e($no) ?></strong><small>Commercial lighting package</small></span><span class="status-pill"><?= e($status) ?></span><b><?= e($amount) ?></b><?= icon('chevron') ?></a><?php endforeach; ?></div></section><section class="account-panel"><div class="panel-head"><h2>Recommended actions</h2></div><div class="action-list"><a href="<?= url('account/quotes') ?>"><?= icon('quote') ?><span><strong>Confirm quotation QT-260721</strong><small>Valid for 12 more days</small></span><?= icon('arrow') ?></a><a href="<?= url('procurement/sample-order') ?>"><?= icon('sample') ?><span><strong>Order samples for AL10</strong><small>Stock available now</small></span><?= icon('arrow') ?></a><a href="<?= url('account/downloads') ?>"><?= icon('download') ?><span><strong>Download latest project files</strong><small>5 new revisions</small></span><?= icon('arrow') ?></a></div></section></div>
<?php elseif(in_array($view,['orders','quotes'],true)): ?>
<div class="account-panel"><div class="panel-head"><h2><?= e($page['title']) ?></h2><label><?= icon('search') ?><input placeholder="Search number or project"></label></div><div class="account-table"><div class="account-table-head"><span>Number</span><span>Project</span><span>Date</span><span>Status</span><span>Amount</span><span></span></div><?php for($i=1;$i<=6;$i++): ?><a href="#"><span><strong><?= $view==='orders'?'SO':'QT' ?>-202607<?= str_pad((string)$i,2,'0',STR_PAD_LEFT) ?></strong></span><span>Lighting package <?= $i ?></span><span>2026-07-<?= 10+$i ?></span><span><b class="status-pill"><?= $i%2?'Under review':'Confirmed' ?></b></span><span>USD <?= number_format(4200+$i*1360) ?></span><span><?= icon('chevron') ?></span></a><?php endfor; ?></div></div>
<?php elseif($view==='wishlist'): ?><div class="product-grid product-grid-three"><?php foreach(array_slice($products,0,6) as $p): ?><?= product_card($p,true) ?><?php endforeach; ?></div>
<?php elseif($view==='compare'): ?><div class="compare-storage"><h2>Saved comparison</h2><p>Products added with the compare button will be stored in the browser for this prototype.</p><a class="button button-dark" href="<?= url('ai/compare-products') ?>">Open comparison tool</a></div>
<?php elseif($view==='downloads'): ?><div class="download-list"><?php foreach(array_slice($products,0,6) as $p): ?><a href="#" data-demo-download><?= icon('file') ?><span><strong><?= e($p['sku']) ?> Technical Pack</strong><small>Datasheet · IES · Installation</small></span><?= icon('download') ?></a><?php endforeach; ?></div>
<?php else: ?><form class="account-settings-form"><div class="form-grid two-columns"><label>Company<input value="Demo Buyer Company"></label><label>Contact name<input value="Demo Buyer"></label><label>Email<input type="email" value="buyer@demo.invalid"></label><label>Phone<input value=""></label><label class="full">Default address<textarea rows="4">Demo address — connect the authenticated customer profile.</textarea></label></div><button type="button" class="button button-dark" data-demo-save>Save changes</button></form>
<?php endif; ?>
</div></div></section>
