<?php declare(strict_types=1); $section=$sections['ai']; ?>
<?= page_intro($page, '<div class="ai-status-card"><span class="live-dot"></span><div><strong>Guided tools active</strong><small>Results are illustrative until connected to the live product rule engine.</small></div></div>') ?>
<section class="section"><div class="container">
<?php if($page['is_root'] ?? false): ?>
<?= child_cards('ai',$section) ?>
<?php else: $tool=$page['slug']; ?>
<div class="tool-shell" data-ai-tool="<?= e($tool) ?>">
    <div class="tool-sidebar"><span class="eyebrow">AI Assistant</span><h2><?= e($page['title']) ?></h2><p>Use the inputs to generate an immediate procurement recommendation.</p><ol><li class="is-active">Enter requirement</li><li>Review result</li><li>Add to RFQ</li></ol><a href="<?= url('ai') ?>">All AI tools <?= icon('arrow') ?></a></div>
    <div class="tool-workspace">
    <?php if($tool==='lighting-calculator'): ?>
        <div class="tool-form"><h3>Estimate fixture quantity</h3><div class="form-grid three-columns"><label>Room length (m)<input type="number" value="10" min="1" step="0.1" data-calc-length></label><label>Room width (m)<input type="number" value="8" min="1" step="0.1" data-calc-width></label><label>Target illuminance (lux)<input type="number" value="500" min="50" step="50" data-calc-lux></label><label>Lumens per fixture<input type="number" value="1200" min="100" step="100" data-calc-lumens></label><label>Utilisation factor<input type="number" value="0.65" min="0.1" max="1" step="0.05" data-calc-uf></label><label>Maintenance factor<input type="number" value="0.8" min="0.1" max="1" step="0.05" data-calc-mf></label></div><button class="button button-dark" type="button" data-calc-lighting>Calculate</button></div>
        <div class="tool-result" data-lighting-result><span>Estimated result</span><strong>65 fixtures</strong><p>Approximate calculation. Final design should be verified with IES files.</p></div>
    <?php elseif($tool==='beam-angle-selector'): ?>
        <div class="tool-form"><h3>Match beam diameter</h3><div class="form-grid two-columns"><label>Mounting height above target (m)<input type="number" value="3" min="0.2" step="0.1" data-beam-height></label><label>Desired beam diameter (m)<input type="number" value="1.3" min="0.1" step="0.1" data-beam-diameter></label></div><button class="button button-dark" type="button" data-calc-beam>Suggest angle</button></div><div class="tool-result" data-beam-result><span>Suggested beam angle</span><strong>24°</strong><p>Nearest standard optic based on geometric beam spread.</p></div>
    <?php elseif($tool==='driver-selector'): ?>
        <div class="tool-form"><h3>Size the LED driver</h3><div class="form-grid three-columns"><label>Fixture wattage<input type="number" value="15" min="1" data-driver-watts></label><label>Fixtures per driver<input type="number" value="1" min="1" data-driver-qty></label><label>Load factor<select data-driver-factor><option value="1.2">20% headroom</option><option value="1.15">15% headroom</option><option value="1.1">10% headroom</option></select></label><label>Dimming<select><option>On / Off</option><option>0–10V</option><option>DALI-2</option></select></label><label>Input voltage<select><option>220–240V</option><option>110–120V</option></select></label><label>Installation<select><option>Independent</option><option>Built-in</option></select></label></div><button class="button button-dark" type="button" data-calc-driver>Select driver</button></div><div class="tool-result" data-driver-result><span>Minimum driver capacity</span><strong>18W</strong><p>Choose the next available compliant driver rating.</p></div>
    <?php elseif($tool==='compare-products'): ?>
        <div class="compare-table"><div class="compare-head"><span>Feature</span><?php foreach(array_slice($products,0,3) as $p): ?><span><img src="<?= asset('img/'.$p['image']) ?>" alt=""><strong><?= e($p['sku']) ?></strong><small><?= e($p['name']) ?></small></span><?php endforeach; ?></div><?php foreach(['Price','Stock','Lead time','Power','Beam','Dimming','IP rating'] as $row): ?><div><span><?= e($row) ?></span><?php foreach(array_slice($products,0,3) as $p): ?><span><?= e(match($row){'Price'=>'USD '.number_format($p['price'],2),'Stock'=>number_format($p['stock']).' pcs','Lead time'=>$p['lead_time'],default=>$p['specs'][$row]??($p['features'][0]??'—')}) ?></span><?php endforeach; ?></div><?php endforeach; ?></div>
    <?php elseif($tool==='ai-consultant'): ?>
        <div class="ai-chat"><div class="chat-message assistant"><div><?= icon('ai') ?></div><p>Tell me the application, mounting height, target effect, quantity and control requirement. I will build a product shortlist.</p></div><div class="chat-suggestions"><button>Retail store, 3.2m ceiling</button><button>Hotel corridor downlights</button><button>Museum track lighting</button><button>DALI linear office lighting</button></div><form data-demo-chat><textarea placeholder="Describe your project or product requirement…"></textarea><button class="button button-dark" type="submit">Send <?= icon('arrow') ?></button></form></div>
    <?php else: ?>
        <form class="finder-form" data-product-finder><div class="form-grid two-columns"><label>Application<select name="application"><option>Retail</option><option>Hospitality</option><option>Office</option><option>Museum</option><option>Residential</option></select></label><label>Installation<select name="installation"><option>Recessed</option><option>Track mounted</option><option>Surface</option><option>Pendant</option></select></label><label>Lighting purpose<select name="purpose"><option>Accent</option><option>General</option><option>Wall washing</option><option>Task</option></select></label><label>Dimming<select name="dimming"><option>On / Off</option><option>0–10V</option><option>DALI-2</option></select></label><label>Mounting height<input type="number" value="3" min="1" step="0.1" name="height"></label><label>Preferred beam<select name="beam"><option>Not sure</option><option>Narrow 15°</option><option>Medium 24°</option><option>Wide 36°+</option></select></label></div><button class="button button-dark" type="submit">Find products</button></form><div class="finder-results" data-finder-results><span class="eyebrow">Recommended starting point</span><h3>Complete the form to generate a shortlist.</h3></div>
    <?php endif; ?>
    </div>
</div>
<?php endif; ?>
</div></section>
