<?php declare(strict_types=1); $section=$sections['projects']; ?>
<?= page_intro($page) ?>
<section class="section"><div class="container">
<?php if($page['is_root'] ?? false): ?>
<?= section_heading('Project library','Filter by project type','Each case connects project context, products, IES files and related solutions.') ?>
<div class="project-card-grid project-card-grid-large"><?php foreach($section['items'] as $slug=>$item): ?><a class="project-card" href="<?= url('projects/'.$slug) ?>"><img src="<?= asset('img/'.scene_image_for($slug)) ?>" alt=""><div><span><?= e($item['title']) ?></span><h3><?= e($item['title']) ?> project references</h3><p>Cases · products · photometrics · solutions</p></div></a><?php endforeach; ?></div>
<?php else: ?>
<div class="project-detail-feature"><div class="project-detail-media"><img src="<?= asset('img/'.scene_image_for($page['slug'])) ?>" alt=""></div><div><span class="eyebrow">Featured case</span><h2><?= e($page['title']) ?> lighting project</h2><p>A template showing how every project page can connect the design brief, selected products, installation conditions, IES files and final outcome.</p><dl><div><dt>Application</dt><dd><?= e($page['title']) ?></dd></div><div><dt>Location</dt><dd>International</dd></div><div><dt>Products</dt><dd>Downlight · Track · Linear</dd></div><div><dt>Controls</dt><dd>DALI-2</dd></div></dl><div class="button-row"><a class="button button-dark" href="<?= url('procurement/project-package') ?>">Request similar package</a><a class="button button-outline" href="<?= url('solutions/'.$page['slug']) ?>">View solution</a></div></div></div>
<div class="project-content-grid"><article><span>01</span><h3>Project requirement</h3><p>Define visual goals, mounting conditions, target illuminance and control needs.</p></article><article><span>02</span><h3>Product selection</h3><p>Show exact models, options, drivers, optics and accessories.</p></article><article><span>03</span><h3>Photometric evidence</h3><p>Link relevant IES files and calculation summaries.</p></article><article><span>04</span><h3>Procurement package</h3><p>Allow visitors to request the same or an adapted package.</p></article></div>
<?= section_heading('Products used','Project product schedule','Example products connected to this project.') ?><div class="product-grid product-grid-four"><?php foreach(array_slice($products,0,4) as $p): ?><?= product_card($p,true) ?><?php endforeach; ?></div>
<?php endif; ?>
</div></section>
