<?php declare(strict_types=1);
$section=$sections['solutions'];
if($page['is_root'] ?? false): ?>
<?= page_intro($page) ?>
<section class="section"><div class="container"><?= section_heading('12 SEO entry pages','Explore by application','Each page uses the same template but different content, product recommendations, FAQs and project evidence.') ?><div class="scene-grid"><?php foreach($section['items'] as $slug=>$item): ?><a class="scene-card" href="<?= url('solutions/'.$slug) ?>"><img src="<?= asset('img/'.scene_image_for($slug)) ?>" alt=""><div class="scene-overlay"><span>Lighting solution</span><h3><?= e($item['title']) ?></h3><p>Design guidance, products, files and project references.</p><strong>Explore solution <?= icon('arrow') ?></strong></div></a><?php endforeach; ?></div></div></section>
<?php else: $slug=$page['slug']; ?>
<section class="solution-hero"><img src="<?= asset('img/'.scene_image_for($slug)) ?>" alt="<?= e($page['title']) ?> lighting"><div class="solution-hero-overlay"></div><div class="container solution-hero-content"><?= breadcrumb($page) ?><span class="eyebrow eyebrow-light"><?= e($page['title']) ?> LIGHTING SOLUTIONS</span><h1>Lighting that supports the <?= e(strtolower($page['title'])) ?> experience.</h1><p>Application guidance, recommended luminaires, photometric resources and a project procurement path in one page.</p><div class="button-row"><a class="button button-light" href="<?= url('procurement/project-package') ?>">Request project package</a><a class="button button-outline-light" href="#recommended">View recommended products</a></div></div></section>
<section class="section"><div class="container solution-priority-grid"><div><span class="eyebrow">Design priorities</span><h2>What matters in <?= e(strtolower($page['title'])) ?> lighting</h2><p>The final content should be written specifically for this application—not duplicated boilerplate.</p></div><div class="priority-cards"><article><strong>01</strong><h3>Visual comfort</h3><p>Control glare, brightness contrast and viewing comfort.</p></article><article><strong>02</strong><h3>Optical precision</h3><p>Match beam distribution to surfaces, displays and task areas.</p></article><article><strong>03</strong><h3>Flexible control</h3><p>Support scenes, dimming, scheduling and future layout changes.</p></article><article><strong>04</strong><h3>Lifecycle value</h3><p>Balance performance, maintenance, energy and replacement parts.</p></article></div></div></section>
<section class="section section-alt" id="recommended"><div class="container"><?= section_heading('Recommended system','Products for '.$page['title'],'A coordinated shortlist including luminaires, drivers and accessories.') ?><div class="product-grid product-grid-four"><?php foreach(array_slice($products,0,4) as $p): ?><?= product_card($p,true) ?><?php endforeach; ?></div></div></section>
<section class="section"><div class="container solution-layout-grid"><div class="solution-diagram"><img src="<?= asset('img/solution-plan.svg') ?>" alt="Lighting plan diagram"></div><div><span class="eyebrow">Typical lighting layers</span><h2>Build the solution as a system</h2><div class="layer-list"><div><span>01</span><strong>Ambient layer</strong><p>Establish comfortable general illumination.</p></div><div><span>02</span><strong>Accent layer</strong><p>Create focus and visual hierarchy.</p></div><div><span>03</span><strong>Vertical layer</strong><p>Illuminate walls, displays and circulation boundaries.</p></div><div><span>04</span><strong>Control layer</strong><p>Define scenes, dimming and operational schedules.</p></div></div></div></div></section>
<section class="section section-alt"><div class="container"><?= section_heading('Evidence','Related '.$page['title'].' projects','See selected products, IES files and the design approach used in completed projects.','projects/'.$slug,'View projects') ?><div class="project-card-grid"><?php for($i=1;$i<=3;$i++): ?><a class="project-card" href="<?= url('projects/'.$slug) ?>"><img src="<?= asset('img/'.scene_image_for($slug)) ?>" alt=""><div><span><?= e($page['title']) ?> · Project <?= $i ?></span><h3>Commercial lighting reference <?= $i ?></h3><p>Product schedule · IES · solution notes</p></div></a><?php endfor; ?></div></div></section>
<?php endif; ?>
